// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package ghostcloud

import (
	fmt "fmt"
	io "io"
	reflect "reflect"
	sync "sync"

	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

var (
	md_Archive         protoreflect.MessageDescriptor
	fd_Archive_type    protoreflect.FieldDescriptor
	fd_Archive_content protoreflect.FieldDescriptor
)

func init() {
	file_ghostcloud_ghostcloud_archive_proto_init()
	md_Archive = File_ghostcloud_ghostcloud_archive_proto.Messages().ByName("Archive")
	fd_Archive_type = md_Archive.Fields().ByName("type")
	fd_Archive_content = md_Archive.Fields().ByName("content")
}

var _ protoreflect.Message = (*fastReflection_Archive)(nil)

type fastReflection_Archive Archive

func (x *Archive) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Archive)(x)
}

func (x *Archive) slowProtoReflect() protoreflect.Message {
	mi := &file_ghostcloud_ghostcloud_archive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Archive_messageType fastReflection_Archive_messageType
var _ protoreflect.MessageType = fastReflection_Archive_messageType{}

type fastReflection_Archive_messageType struct{}

func (x fastReflection_Archive_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Archive)(nil)
}
func (x fastReflection_Archive_messageType) New() protoreflect.Message {
	return new(fastReflection_Archive)
}
func (x fastReflection_Archive_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Archive
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Archive) Descriptor() protoreflect.MessageDescriptor {
	return md_Archive
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Archive) Type() protoreflect.MessageType {
	return _fastReflection_Archive_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Archive) New() protoreflect.Message {
	return new(fastReflection_Archive)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Archive) Interface() protoreflect.ProtoMessage {
	return (*Archive)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Archive) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Type_ != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.Type_))
		if !f(fd_Archive_type, value) {
			return
		}
	}
	if len(x.Content) != 0 {
		value := protoreflect.ValueOfBytes(x.Content)
		if !f(fd_Archive_content, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Archive) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "ghostcloud.ghostcloud.Archive.type":
		return x.Type_ != 0
	case "ghostcloud.ghostcloud.Archive.content":
		return len(x.Content) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ghostcloud.ghostcloud.Archive"))
		}
		panic(fmt.Errorf("message ghostcloud.ghostcloud.Archive does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Archive) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "ghostcloud.ghostcloud.Archive.type":
		x.Type_ = 0
	case "ghostcloud.ghostcloud.Archive.content":
		x.Content = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ghostcloud.ghostcloud.Archive"))
		}
		panic(fmt.Errorf("message ghostcloud.ghostcloud.Archive does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Archive) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "ghostcloud.ghostcloud.Archive.type":
		value := x.Type_
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	case "ghostcloud.ghostcloud.Archive.content":
		value := x.Content
		return protoreflect.ValueOfBytes(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ghostcloud.ghostcloud.Archive"))
		}
		panic(fmt.Errorf("message ghostcloud.ghostcloud.Archive does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Archive) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "ghostcloud.ghostcloud.Archive.type":
		x.Type_ = (ArchiveType)(value.Enum())
	case "ghostcloud.ghostcloud.Archive.content":
		x.Content = value.Bytes()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ghostcloud.ghostcloud.Archive"))
		}
		panic(fmt.Errorf("message ghostcloud.ghostcloud.Archive does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Archive) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ghostcloud.ghostcloud.Archive.type":
		panic(fmt.Errorf("field type of message ghostcloud.ghostcloud.Archive is not mutable"))
	case "ghostcloud.ghostcloud.Archive.content":
		panic(fmt.Errorf("field content of message ghostcloud.ghostcloud.Archive is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ghostcloud.ghostcloud.Archive"))
		}
		panic(fmt.Errorf("message ghostcloud.ghostcloud.Archive does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Archive) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ghostcloud.ghostcloud.Archive.type":
		return protoreflect.ValueOfEnum(0)
	case "ghostcloud.ghostcloud.Archive.content":
		return protoreflect.ValueOfBytes(nil)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ghostcloud.ghostcloud.Archive"))
		}
		panic(fmt.Errorf("message ghostcloud.ghostcloud.Archive does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Archive) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in ghostcloud.ghostcloud.Archive", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Archive) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Archive) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Archive) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Archive) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Archive)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Type_ != 0 {
			n += 1 + runtime.Sov(uint64(x.Type_))
		}
		l = len(x.Content)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Archive)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Content) > 0 {
			i -= len(x.Content)
			copy(dAtA[i:], x.Content)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Content)))
			i--
			dAtA[i] = 0x12
		}
		if x.Type_ != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Type_))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Archive)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Archive: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Archive: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Type_", wireType)
				}
				x.Type_ = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Type_ |= ArchiveType(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Content = append(x.Content[:0], dAtA[iNdEx:postIndex]...)
				if x.Content == nil {
					x.Content = []byte{}
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: ghostcloud/ghostcloud/archive.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArchiveType int32

const (
	ArchiveType_Zip ArchiveType = 0
)

// Enum value maps for ArchiveType.
var (
	ArchiveType_name = map[int32]string{
		0: "Zip",
	}
	ArchiveType_value = map[string]int32{
		"Zip": 0,
	}
)

func (x ArchiveType) Enum() *ArchiveType {
	p := new(ArchiveType)
	*p = x
	return p
}

func (x ArchiveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArchiveType) Descriptor() protoreflect.EnumDescriptor {
	return file_ghostcloud_ghostcloud_archive_proto_enumTypes[0].Descriptor()
}

func (ArchiveType) Type() protoreflect.EnumType {
	return &file_ghostcloud_ghostcloud_archive_proto_enumTypes[0]
}

func (x ArchiveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArchiveType.Descriptor instead.
func (ArchiveType) EnumDescriptor() ([]byte, []int) {
	return file_ghostcloud_ghostcloud_archive_proto_rawDescGZIP(), []int{0}
}

type Archive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type_   ArchiveType `protobuf:"varint,1,opt,name=type,proto3,enum=ghostcloud.ghostcloud.ArchiveType" json:"type,omitempty"`
	Content []byte      `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // This can be large
}

func (x *Archive) Reset() {
	*x = Archive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ghostcloud_ghostcloud_archive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Archive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Archive) ProtoMessage() {}

// Deprecated: Use Archive.ProtoReflect.Descriptor instead.
func (*Archive) Descriptor() ([]byte, []int) {
	return file_ghostcloud_ghostcloud_archive_proto_rawDescGZIP(), []int{0}
}

func (x *Archive) GetType_() ArchiveType {
	if x != nil {
		return x.Type_
	}
	return ArchiveType_Zip
}

func (x *Archive) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_ghostcloud_ghostcloud_archive_proto protoreflect.FileDescriptor

var file_ghostcloud_ghostcloud_archive_proto_rawDesc = []byte{
	0x0a, 0x23, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x67, 0x68, 0x6f,
	0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x22, 0x5b, 0x0a, 0x07,
	0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x41, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2a, 0x16, 0x0a, 0x0b, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x5a, 0x69, 0x70, 0x10,
	0x00, 0x42, 0xda, 0x01, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x42,
	0x0c, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x66, 0x74,
	0x65, 0x64, 0x69, 0x6e, 0x69, 0x74, 0x2f, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2f, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0xa2, 0x02, 0x03, 0x47, 0x47,
	0x58, 0xaa, 0x02, 0x15, 0x47, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x47,
	0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0xca, 0x02, 0x15, 0x47, 0x68, 0x6f, 0x73,
	0x74, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5c, 0x47, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0xe2, 0x02, 0x21, 0x47, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5c, 0x47,
	0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x16, 0x47, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x3a, 0x3a, 0x47, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ghostcloud_ghostcloud_archive_proto_rawDescOnce sync.Once
	file_ghostcloud_ghostcloud_archive_proto_rawDescData = file_ghostcloud_ghostcloud_archive_proto_rawDesc
)

func file_ghostcloud_ghostcloud_archive_proto_rawDescGZIP() []byte {
	file_ghostcloud_ghostcloud_archive_proto_rawDescOnce.Do(func() {
		file_ghostcloud_ghostcloud_archive_proto_rawDescData = protoimpl.X.CompressGZIP(file_ghostcloud_ghostcloud_archive_proto_rawDescData)
	})
	return file_ghostcloud_ghostcloud_archive_proto_rawDescData
}

var file_ghostcloud_ghostcloud_archive_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ghostcloud_ghostcloud_archive_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ghostcloud_ghostcloud_archive_proto_goTypes = []interface{}{
	(ArchiveType)(0), // 0: ghostcloud.ghostcloud.ArchiveType
	(*Archive)(nil),  // 1: ghostcloud.ghostcloud.Archive
}
var file_ghostcloud_ghostcloud_archive_proto_depIdxs = []int32{
	0, // 0: ghostcloud.ghostcloud.Archive.type:type_name -> ghostcloud.ghostcloud.ArchiveType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ghostcloud_ghostcloud_archive_proto_init() }
func file_ghostcloud_ghostcloud_archive_proto_init() {
	if File_ghostcloud_ghostcloud_archive_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ghostcloud_ghostcloud_archive_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Archive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ghostcloud_ghostcloud_archive_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ghostcloud_ghostcloud_archive_proto_goTypes,
		DependencyIndexes: file_ghostcloud_ghostcloud_archive_proto_depIdxs,
		EnumInfos:         file_ghostcloud_ghostcloud_archive_proto_enumTypes,
		MessageInfos:      file_ghostcloud_ghostcloud_archive_proto_msgTypes,
	}.Build()
	File_ghostcloud_ghostcloud_archive_proto = out.File
	file_ghostcloud_ghostcloud_archive_proto_rawDesc = nil
	file_ghostcloud_ghostcloud_archive_proto_goTypes = nil
	file_ghostcloud_ghostcloud_archive_proto_depIdxs = nil
}
