# ghostcloud-cosmos CI
# The Lifted Initiative
version: 2.1

GO_VERSION: &go_version '1.21'

orbs:
  go: circleci/go@1.9.0
  codecov: codecov/codecov@3.3.0

jobs:
  build:
    executor:
      name: go/default
      tag: *go_version
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: make coverage
      - codecov/upload:
          file: coverage-filtered.out
      - go/install-goreleaser:
          version: v1.22.1
      # Use go/goreleaser-release when GITHUB_TOKEN is set
      - run: goreleaser release --snapshot --clean
      - run:
          name: move artifacts
          command: |
              mkdir -p /tmp/artifacts
              mv dist/ghostcloudd_*.tar.gz dist/ghostcloudd_*.txt /tmp/artifacts
      - store_artifacts:
            path: /tmp/artifacts
  security:
    executor:
      name: go/default
      tag: *go_version
    steps:
      - checkout
      - run: make vet
      - run: make govulncheck

workflows:
  main:
    jobs:
      - build
      - security
