# ghostcloud-cosmos CI
# The Lifted Initiative
version: 2.1

GO_VERSION: &go_version '1.21'
GORELEASER_VERSION: &goreleaser_version 'v1.22.1'

orbs:
  go: circleci/go@1.9.0
  codecov: codecov/codecov@3.3.0

jobs:
  build:
    executor:
      name: go/default
      tag: *go_version
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: make coverage
      - codecov/upload:
          file: coverage-filtered.out
      - go/install-goreleaser:
          version: *goreleaser_version
      - run: goreleaser release --snapshot --clean
      - run:
          name: move artifacts
          command: |
              mkdir -p /tmp/artifacts
              mv dist/ghostcloudd_*.tar.gz dist/ghostcloudd_*.txt /tmp/artifacts
      - store_artifacts:
            path: /tmp/artifacts
  security:
    executor:
      name: go/default
      tag: *go_version
    steps:
      - checkout
      - run: make vet
      - run: make govulncheck
  release:
    executor:
      name: go/default
      tag: *go_version
    resource_class: xlarge
    steps:
      - checkout
      - go/install-goreleaser:
          version: *goreleaser_version
      - go/goreleaser-release:
          project-path: "${HOME}/project"
          publish-release: true

workflows:
  main:
    jobs:
      - build
      - security
  release:
    jobs:
      - release:
          context:
            - GITHUB_CREDS
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^v?\d(\.\d){2}$/ # e.g. major, minor, patch (0.1.1)
                - /^v?\d(\.\d){2}(-[\w-]+(\.[\w-]+)?)$/ # prereleases (0.1.1-alpha.8)