// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ghostcloud/ghostcloud/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	MaxPayloadSize      int64  `protobuf:"varint,1,opt,name=max_payload_size,json=maxPayloadSize,proto3" json:"max_payload_size,omitempty"`
	MaxNameSize         int64  `protobuf:"varint,2,opt,name=max_name_size,json=maxNameSize,proto3" json:"max_name_size,omitempty"`
	MaxDescriptionSize  int64  `protobuf:"varint,3,opt,name=max_description_size,json=maxDescriptionSize,proto3" json:"max_description_size,omitempty"`
	MaxUncompressedSize uint64 `protobuf:"varint,4,opt,name=max_uncompressed_size,json=maxUncompressedSize,proto3" json:"max_uncompressed_size,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d0bbb6eb8def319, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxPayloadSize() int64 {
	if m != nil {
		return m.MaxPayloadSize
	}
	return 0
}

func (m *Params) GetMaxNameSize() int64 {
	if m != nil {
		return m.MaxNameSize
	}
	return 0
}

func (m *Params) GetMaxDescriptionSize() int64 {
	if m != nil {
		return m.MaxDescriptionSize
	}
	return 0
}

func (m *Params) GetMaxUncompressedSize() uint64 {
	if m != nil {
		return m.MaxUncompressedSize
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "ghostcloud.ghostcloud.Params")
}

func init() {
	proto.RegisterFile("ghostcloud/ghostcloud/params.proto", fileDescriptor_0d0bbb6eb8def319)
}

var fileDescriptor_0d0bbb6eb8def319 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0x31, 0x4b, 0xfb, 0x40,
	0x18, 0x06, 0xf0, 0xdc, 0xbf, 0xa1, 0xc3, 0xfd, 0x51, 0x24, 0xb6, 0x20, 0x0e, 0x67, 0xc9, 0x94,
	0x29, 0x11, 0xbb, 0x39, 0x8a, 0xab, 0x52, 0x2a, 0x2e, 0x2e, 0xe5, 0x6d, 0x72, 0xa6, 0x07, 0xb9,
	0xbc, 0x47, 0xee, 0x02, 0xd7, 0x7e, 0x0a, 0x47, 0x47, 0x3f, 0x8b, 0x93, 0x63, 0x47, 0x47, 0x49,
	0xbe, 0x88, 0xe4, 0x22, 0x24, 0xdb, 0x93, 0x3c, 0xbf, 0x07, 0x8e, 0x97, 0x86, 0xf9, 0x0e, 0xb5,
	0x49, 0x0b, 0xac, 0xb3, 0x64, 0x14, 0x15, 0x54, 0x20, 0x75, 0xac, 0x2a, 0x34, 0x18, 0xcc, 0x87,
	0x22, 0x1e, 0xe2, 0xe5, 0x2c, 0xc7, 0x1c, 0x9d, 0x48, 0xba, 0xd4, 0xe3, 0xf0, 0x93, 0xd0, 0xe9,
	0xca, 0xad, 0x83, 0x88, 0x9e, 0x49, 0xb0, 0x1b, 0x05, 0xfb, 0x02, 0x21, 0xdb, 0x68, 0x71, 0xe0,
	0x17, 0x64, 0x41, 0xa2, 0xc9, 0xfa, 0x54, 0x82, 0x5d, 0xf5, 0xbf, 0x9f, 0xc4, 0x81, 0x07, 0x21,
	0x3d, 0xe9, 0x64, 0x09, 0x92, 0xf7, 0xec, 0x9f, 0x63, 0xff, 0x25, 0xd8, 0x47, 0x90, 0xdc, 0x99,
	0x6b, 0x3a, 0xeb, 0x4c, 0xc6, 0x75, 0x5a, 0x09, 0x65, 0x04, 0x96, 0x3d, 0x9d, 0x38, 0x1a, 0x48,
	0xb0, 0xf7, 0x43, 0xe5, 0x16, 0x37, 0x74, 0xde, 0x2d, 0xea, 0x32, 0x45, 0xa9, 0x2a, 0xae, 0x35,
	0xff, 0x7b, 0x84, 0xbf, 0x20, 0x91, 0xbf, 0x3e, 0x97, 0x60, 0x9f, 0x47, 0x5d, 0xb7, 0xb9, 0xf5,
	0xdf, 0x3f, 0xae, 0xbc, 0xbb, 0x87, 0xaf, 0x86, 0x91, 0x63, 0xc3, 0xc8, 0x4f, 0xc3, 0xc8, 0x5b,
	0xcb, 0xbc, 0x63, 0xcb, 0xbc, 0xef, 0x96, 0x79, 0x2f, 0xcb, 0x5c, 0x98, 0x5d, 0xbd, 0x8d, 0x53,
	0x94, 0x49, 0x21, 0x5e, 0x0d, 0xcf, 0x44, 0x29, 0xcc, 0xf8, 0x74, 0x76, 0xfc, 0x61, 0xf6, 0x8a,
	0xeb, 0xed, 0xd4, 0x9d, 0x66, 0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x99, 0x36, 0xeb, 0x6d,
	0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxUncompressedSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxUncompressedSize))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxDescriptionSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxDescriptionSize))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxNameSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxNameSize))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxPayloadSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPayloadSize))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxPayloadSize != 0 {
		n += 1 + sovParams(uint64(m.MaxPayloadSize))
	}
	if m.MaxNameSize != 0 {
		n += 1 + sovParams(uint64(m.MaxNameSize))
	}
	if m.MaxDescriptionSize != 0 {
		n += 1 + sovParams(uint64(m.MaxDescriptionSize))
	}
	if m.MaxUncompressedSize != 0 {
		n += 1 + sovParams(uint64(m.MaxUncompressedSize))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPayloadSize", wireType)
			}
			m.MaxPayloadSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPayloadSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxNameSize", wireType)
			}
			m.MaxNameSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxNameSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDescriptionSize", wireType)
			}
			m.MaxDescriptionSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDescriptionSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxUncompressedSize", wireType)
			}
			m.MaxUncompressedSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxUncompressedSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
